export default function Journal() {
  return (
    <section id="journal" data-screen-label="Journal" style={{ padding: "clamp(56px,7vw,100px) clamp(20px,4vw,56px)" }}>
      <div style={{ maxWidth: "1440px", margin: "0 auto", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,440px),1fr))", gap: "clamp(32px,5vw,72px)" }}>
        <div style={{ display: "flex", flexDirection: "column", gap: "18px" }}>
          <p style={{ fontFamily: "'IBM Plex Mono'", fontSize: "12px", letterSpacing: ".12em", textTransform: "uppercase", color: "#55566a" }}>Journal</p>
          <h2 style={{ fontFamily: "'Barlow Condensed'", fontWeight: "800", fontSize: "clamp(40px,4.6vw,72px)", lineHeight: ".92", textTransform: "uppercase" }}><span style={{ display: "block", overflow: "hidden" }}><span data-r="mask" style={{ display: "block" }}>Sharp notes from SEO,</span></span><span style={{ display: "block", overflow: "hidden" }}><span data-r="mask" data-d="70" style={{ display: "block" }}>websites, AI systems,</span></span><span style={{ display: "block", overflow: "hidden" }}><span data-r="mask" data-d="140" style={{ display: "block" }}>and performance work.</span></span></h2>
          <p data-r="up" style={{ color: "#55566a", fontSize: "17px", lineHeight: "1.6", maxWidth: "480px" }}>Compact reads for founders and growth teams who want clearer digital execution, not recycled advice.</p>
          <a className="hv4" data-r="up" href="#journal" style={{ marginTop: "8px", alignSelf: "flex-start", display: "flex", flexDirection: "column", gap: "14px", padding: "26px", borderRadius: "8px", background: "#080b38", color: "#fff", maxWidth: "520px" }}>
            <span style={{ display: "flex", gap: "10px", fontFamily: "'IBM Plex Mono'", fontSize: "12px" }}><span style={{ color: "#ffc83d" }}>Featured article</span><span style={{ opacity: ".6" }}>Strategy</span></span>
            <span style={{ fontFamily: "'Barlow Condensed'", fontWeight: "700", fontSize: "clamp(28px,2.6vw,38px)", lineHeight: "1", textTransform: "uppercase" }}>AI Marketing Stack for UK Growth Teams in 2026</span>
            <span style={{ color: "rgba(255,255,255,.7)", fontSize: "15px", lineHeight: "1.5" }}>How teams are using AI-assisted workflows to shorten campaign cycles while improving conversion quality.</span>
            <span style={{ display: "flex", gap: "16px", fontSize: "13px", color: "rgba(255,255,255,.6)" }}><span>Mar 02, 2026</span><span>6 min read</span><span style={{ color: "#fff", fontWeight: "600", marginLeft: "auto" }}>Read ↗</span></span>
          </a>
        </div>
        <div style={{ display: "flex", flexDirection: "column", borderTop: "2px solid #0a0c24", alignSelf: "start" }}>
          <a className="hv5" data-r="up" href="#journal" style={{ display: "flex", flexDirection: "column", gap: "8px", padding: "24px 0", borderBottom: "1px solid rgba(10,12,36,.14)", transition: "padding .3s" }}><span style={{ display: "flex", justifyContent: "space-between", fontFamily: "'IBM Plex Mono'", fontSize: "12px", color: "#3a5bff" }}><span>SEO</span><span style={{ color: "#55566a" }}>Feb 24, 2026 · 4 min read</span></span><span style={{ fontFamily: "'Barlow Condensed'", fontWeight: "700", fontSize: "30px", lineHeight: "1", textTransform: "uppercase" }}>SEO + Automation: A Practical Framework</span><span style={{ color: "#55566a", fontSize: "15px", lineHeight: "1.5" }}>A clear process for combining intent-focused content with automated optimisation for scale.</span></a>
          <a className="hv5" data-r="up" data-d="60" href="#journal" style={{ display: "flex", flexDirection: "column", gap: "8px", padding: "24px 0", borderBottom: "1px solid rgba(10,12,36,.14)", transition: "padding .3s" }}><span style={{ display: "flex", justifyContent: "space-between", fontFamily: "'IBM Plex Mono'", fontSize: "12px", color: "#3a5bff" }}><span>Product Marketing</span><span style={{ color: "#55566a" }}>Feb 11, 2026 · 7 min read</span></span><span style={{ fontFamily: "'Barlow Condensed'", fontWeight: "700", fontSize: "30px", lineHeight: "1", textTransform: "uppercase" }}>Building High-Performing SaaS Landing Pages</span><span style={{ color: "#55566a", fontSize: "15px", lineHeight: "1.5" }}>Design and messaging patterns that reduce drop-off and increase qualified demo requests.</span></a>
          <a className="hv5" data-r="up" data-d="120" href="#journal" style={{ display: "flex", flexDirection: "column", gap: "8px", padding: "24px 0", borderBottom: "1px solid rgba(10,12,36,.14)", transition: "padding .3s" }}><span style={{ display: "flex", justifyContent: "space-between", fontFamily: "'IBM Plex Mono'", fontSize: "12px", color: "#3a5bff" }}><span>Paid Media</span><span style={{ color: "#55566a" }}>Jan 30, 2026 · 5 min read</span></span><span style={{ fontFamily: "'Barlow Condensed'", fontWeight: "700", fontSize: "30px", lineHeight: "1", textTransform: "uppercase" }}>Creative Testing Loops for Paid Social</span><span style={{ color: "#55566a", fontSize: "15px", lineHeight: "1.5" }}>A repeatable creative cycle for finding top-performing ad variants without burning budget.</span></a>
          <a className="hv5" data-r="up" data-d="180" href="#journal" style={{ display: "flex", flexDirection: "column", gap: "8px", padding: "24px 0", borderBottom: "1px solid rgba(10,12,36,.14)", transition: "padding .3s" }}><span style={{ display: "flex", justifyContent: "space-between", fontFamily: "'IBM Plex Mono'", fontSize: "12px", color: "#3a5bff" }}><span>Analytics</span><span style={{ color: "#55566a" }}>Jan 14, 2026 · 5 min read</span></span><span style={{ fontFamily: "'Barlow Condensed'", fontWeight: "700", fontSize: "30px", lineHeight: "1", textTransform: "uppercase" }}>Analytics Views Every Founder Should Track Weekly</span><span style={{ color: "#55566a", fontSize: "15px", lineHeight: "1.5" }}>The dashboard cuts that keep leadership focused on outcomes instead of vanity metrics.</span></a>
          <a href="#journal" style={{ padding: "20px 0", fontWeight: "600" }}>View all articles →</a>
        </div>
      </div>
    </section>
  );
}
