export default function WhyUs() {
  return (
    <section data-screen-label="Why us" style={{ padding: "clamp(64px,8vw,120px) clamp(20px,4vw,56px)" }}>
      <div style={{ maxWidth: "1440px", margin: "0 auto", display: "flex", flexDirection: "column", gap: "clamp(32px,4vw,56px)" }}>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,440px),1fr))", gap: "24px 64px", alignItems: "end" }}>
          <h2 style={{ fontFamily: "'Barlow Condensed'", fontWeight: "800", fontSize: "clamp(44px,5.4vw,84px)", lineHeight: ".9", textTransform: "uppercase" }}><span style={{ display: "block", overflow: "hidden" }}><span data-r="mask" style={{ display: "block" }}>Why UK Businesses</span></span><span style={{ display: "block", overflow: "hidden" }}><span data-r="mask" data-d="80" style={{ display: "block" }}>Choose Us</span></span></h2>
          <div data-r="up" data-d="100" style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
            <p style={{ fontWeight: "600", fontSize: "18px" }}>Why UK Businesses Trust Our AI-Powered Digital Marketing Agency</p>
            <p style={{ color: "#55566a", fontSize: "17px", lineHeight: "1.6", textWrap: "pretty" }}>UK businesses need more than visibility - they need strategy and measurable results. We combine AI-driven insight, creative execution, and data-backed marketing systems to deliver stronger conversion performance and sustainable digital growth.</p>
          </div>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,210px),1fr))", gap: "0" }}>
          <div data-r="up" data-d="0" style={{ position: "relative", padding: "26px 22px 30px 0", display: "flex", flexDirection: "column", gap: "40px" }}><span data-r="bar" data-d="100" style={{ position: "absolute", left: "0", right: "12px", top: "0", height: "3px", background: "#0a0c24", transformOrigin: "0 50%" }}></span><span style={{ fontFamily: "'IBM Plex Mono'", fontSize: "12px", color: "#3a5bff" }}>01</span><p style={{ fontFamily: "'Barlow Condensed'", fontWeight: "700", fontSize: "30px", lineHeight: "1", textTransform: "uppercase" }}>AI-Integrated Marketing Approach</p></div>
          <div data-r="up" data-d="80" style={{ position: "relative", padding: "26px 22px 30px 0", display: "flex", flexDirection: "column", gap: "40px" }}><span data-r="bar" data-d="180" style={{ position: "absolute", left: "0", right: "12px", top: "0", height: "3px", background: "#0a0c24", transformOrigin: "0 50%" }}></span><span style={{ fontFamily: "'IBM Plex Mono'", fontSize: "12px", color: "#3a5bff" }}>02</span><p style={{ fontFamily: "'Barlow Condensed'", fontWeight: "700", fontSize: "30px", lineHeight: "1", textTransform: "uppercase" }}>ROI-Focused Campaigns</p></div>
          <div data-r="up" data-d="160" style={{ position: "relative", padding: "26px 22px 30px 0", display: "flex", flexDirection: "column", gap: "40px" }}><span data-r="bar" data-d="260" style={{ position: "absolute", left: "0", right: "12px", top: "0", height: "3px", background: "#0a0c24", transformOrigin: "0 50%" }}></span><span style={{ fontFamily: "'IBM Plex Mono'", fontSize: "12px", color: "#3a5bff" }}>03</span><p style={{ fontFamily: "'Barlow Condensed'", fontWeight: "700", fontSize: "30px", lineHeight: "1", textTransform: "uppercase" }}>Transparent Reporting</p></div>
          <div data-r="up" data-d="240" style={{ position: "relative", padding: "26px 22px 30px 0", display: "flex", flexDirection: "column", gap: "40px" }}><span data-r="bar" data-d="340" style={{ position: "absolute", left: "0", right: "12px", top: "0", height: "3px", background: "#0a0c24", transformOrigin: "0 50%" }}></span><span style={{ fontFamily: "'IBM Plex Mono'", fontSize: "12px", color: "#3a5bff" }}>04</span><p style={{ fontFamily: "'Barlow Condensed'", fontWeight: "700", fontSize: "30px", lineHeight: "1", textTransform: "uppercase" }}>Full-Service In-House Team</p></div>
          <div data-r="up" data-d="320" style={{ position: "relative", padding: "26px 22px 30px 0", display: "flex", flexDirection: "column", gap: "40px" }}><span data-r="bar" data-d="420" style={{ position: "absolute", left: "0", right: "12px", top: "0", height: "3px", background: "#ffc83d", transformOrigin: "0 50%" }}></span><span style={{ fontFamily: "'IBM Plex Mono'", fontSize: "12px", color: "#3a5bff" }}>05</span><p style={{ fontFamily: "'Barlow Condensed'", fontWeight: "700", fontSize: "30px", lineHeight: "1", textTransform: "uppercase" }}>Custom Growth Strategies</p></div>
        </div>
      </div>
    </section>
  );
}
